projectcm-original/projectcm/urls.py
from django.contrib import admin, auth
from django.urls import path, include
import projectcm_core.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', projectcm_core.views.index),
    path('projects/', include('projectcm_core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projectcm-original/projectcm_core/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.listprojects, name='project_home'),
	path('manage/company', views.company_manage_lists, name='company_manage'),
	path('manage/company/<int:companyid>/modify', views.company_manage_modify, name='company_manage_modify'),
	path('manage/company/<int:companyid>/modify/addstaff', views.add_staff_from_existing, name='add_staff_existing'),
	path('task/<int:taskid>', views.project_task_member_modify, name='task_modify'),
	path('<int:projectid>', views.project_show, name='project_show'),
	path('new', views.project_new, name='project_new'),
	path('manage', views.project_listall, name='project_listall'),
	path('manage/<int:projectid>/modify', views.project_modify, name='project_modify'),
	path('manage/<int:projectid>/delete', views.project_delete, name='project_delete'),
	path('manage/<int:projectid>/role', views.project_role_list, name='project_role_list'),
	path('manage/<int:projectid>/role/<int:roleid>/modify', views.project_role_modify, name='project_role_modify'),
	path('manage/<int:projectid>/role/add', views.project_role_add, name='project_role_add'),
	path('manage/<int:projectid>/role/<int:roleid>/delete', views.project_role_delete, name='project_role_delete'),
	path('manage/<int:projectid>/task', views.project_task_list, name='project_task_list'),
	path('manage/<int:projectid>/task/add', views.project_task_add, name='project_task_add'),
	path('manage/<int:projectid>/task/<int:taskid>/up', views.project_task_up),
	path('manage/<int:projectid>/task/<int:taskid>/down', views.project_task_down),
	path('manage/<int:projectid>/task/<int:taskid>/modify', views.project_task_modify, name='project_task_modify'),
	path('manage/<int:projectid>/task/<int:taskid>/delete', views.project_task_delete, name='project_task_delete'),
]

projectcm-original/projectcm_core/models.py
from django.db import models
from django.db.models import Max, Q
from django.contrib.auth.models import User, Group

class Holiday(models.Model):
	name = models.CharField(max_length=50, default="default")
	sundayWork = models.BooleanField(default=False)
	saturdayWork = models.BooleanField(default=False)
	fridayWork = models.BooleanField(default=True)
	thursdayWork = models.BooleanField(default=True)
	wednesdayWork = models.BooleanField(default=True)
	tuesdayWork = models.BooleanField(default=True)
	mondayWork = models.BooleanField(default=True)
	def __str__(self):
		return self.name

class PublicHoliday(models.Model):
	holiday = models.ForeignKey(Holiday, on_delete=models.CASCADE)
	holiday_date = models.DateField(null=False, blank=False)
	holiday_description = models.CharField(max_length=40)


class Company(models.Model):
	company_type_choice = (
		["Private", "Private Company"],
		["Public", "Public Company"],
	)

	company_type = models.CharField(max_length=20, choices=company_type_choice, default="Private")
	company_name = models.CharField(max_length=100)
	staffs = models.ManyToManyField(User, null=True, blank=True, default=None)
	company_group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True, default=None)
	holiday = models.ForeignKey(Holiday, on_delete=models.CASCADE, null=True, blank=True, default=None)
	def __str__(self):
		return self.company_name
	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		if self.company_group == None:
			newgroup = Group()
			newgroup.name = str(self.id) + "_" + self.company_name + "_Admin"
			newgroup.save()
			self.company_group = newgroup
			super().save(*args, **kwargs)		


class Project(models.Model):
	pjname = models.CharField(max_length=20)
	company = models.ForeignKey(Company, on_delete=models.CASCADE,)
	created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)
	def __str__(self):
		return self.company.company_name + ":" + self.pjname
	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		#if after save, the project created_by is changed and the created_by person has no role, add a role for this user
		if not ProjectRole.objects.filter(project__id=self.id, projectuser__id=self.created_by.id):
			role = ProjectRole()
			role.project = self
			role.projectuser = self.created_by
			role.save()
		
		

class ProjectRole(models.Model):
	PM = 'PM'
	MEMBER = 'Member'
	STACKHOLDER = 'Stackholder'
	projectuser = models.ForeignKey(User, on_delete=models.CASCADE,)
	projectrole_choice = (
		(PM, 'Project Manager'),
		(MEMBER, 'Project Member'),
		(STACKHOLDER, 'Project Stackholder'),	
	)
	projectrole = models.CharField(max_length=20, choices=projectrole_choice, default=STACKHOLDER)
	project = models.ForeignKey(Project, on_delete=models.CASCADE,)

class Task(models.Model):
	OPEN = 'OPEN'
	INPROGRESS = 'INPROGRESS'
	COMPLETED = 'COMPLETED'
	taskstatus_choice = (
		(OPEN, 'Open - Not completed'),
		(INPROGRESS, 'Work In Progress'),
		(COMPLETED, 'Completed'),
	)
	taskname = models.CharField(max_length=40)
	taskdescription = models.TextField(max_length=100, null=True, blank=True)
	plannedstartdate = models.DateField(null=True,blank=True, default=None)
	plannedcompletedate = models.DateField(null=True,blank=True, default=None)
	actualstartdate = models.DateField(null=True,blank=True, default=None)
	actualcompletedate = models.DateField(null=True,blank=True, default=None)
	ownedby = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, blank=True,null=True)
	project = models.ForeignKey(Project, on_delete=models.CASCADE,)
	projecttaskid = models.IntegerField(default=None, editable=False, null=True)
	dependencetask = models.ForeignKey('self', default=None, blank=True, null=True, on_delete=models.SET_NULL)
	plannedresource = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=6, default=None)
	actualresource = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=6, default=None)
	taskstatus = models.CharField(max_length=20, choices=taskstatus_choice, default='OPEN')
	def moveup(self):
		# if it is a move up, swap the project task id with the previous numbered project task id
		this_task_num = self.projecttaskid
		max_task_num = Task.objects.filter(project = self.project).aggregate(Max('projecttaskid'))

		if not this_task_num:
			if max_task_num:
				self.projecttaskid = max_task_num['projecttaskid__max'] + 1
				self.save()
			else:
				self.projecttaskid = 1
				self.save()
		else:
			previous_task = Task.objects.filter(Q(project = self.project), Q(projecttaskid__lt = this_task_num)).order_by('-projecttaskid')
			if previous_task:
				previous_task_num = previous_task[0].projecttaskid
				previous_task[0].projecttaskid = this_task_num
				self.projecttaskid = previous_task_num
				previous_task[0].save()
				self.save()
			 #otherwise, do nothing, can not move up anymore.

	def movedown(self):
		# if it is a move up, swap the project task id with the previous numbered project task id
		this_task_num = self.projecttaskid
		max_task_num = Task.objects.filter(project = self.project).aggregate(Max('projecttaskid'))

		if not this_task_num:
			if max_task_num:
				self.projecttaskid = max_task_num['projecttaskid__max'] + 1
				self.save()
			else:
				self.projecttaskid = 1
				self.save()
		else:
			next_task = Task.objects.filter(Q(project = self.project), Q(projecttaskid__gt = this_task_num)).order_by('projecttaskid')
			if next_task:
				next_task_num = next_task[0].projecttaskid
				next_task[0].projecttaskid = this_task_num
				self.projecttaskid = next_task_num
				next_task[0].save()
				self.save()
			 #otherwise, do nothing, can not move down anymore.
				

	def save(self):
		# assign a project next task id for this task if this field is empty
		if not self.projecttaskid:
			if self.project:
				max_task_num = Task.objects.filter(project = self.project).aggregate(Max('projecttaskid'))
				if max_task_num['projecttaskid__max'] == None:
					self.projecttaskid = 1
				else:
					self.projecttaskid = max_task_num['projecttaskid__max'] + 1
		if self.actualstartdate and self.actualcompletedate:
			# if actual start date and complete date are present
			# change the project status to completed
			self.taskstatus = self.COMPLETED
		if self.actualstartdate and not self.actualcompletedate:
			self.taskstatus = self.INPROGRESS

		super().save()

		

projectcm-original/projectcm_core/forms.py
from django import forms
from django.forms import DateInput
from .models import Project, ProjectRole, Task, Company

class CompanyForm(forms.ModelForm):
	class Meta:
		model = Company
		fields = ('company_name','staffs')
		labels = {
			'company_name': 'Company name',
			'staffs': 'Company staffs',
		}


class ProjectForm(forms.ModelForm):
	
	class Meta:
		model = Project
		fields = ('pjname','company')
		labels = {
			'pjname': 'Project Name',
		}

class ProjectRoleForm(forms.ModelForm):
	class Meta:
		model = ProjectRole
		fields = ('projectuser', 'projectrole')
		labels = {
			'projectuser': 'Project Member',
			'projectrole': 'Member\'s Role',
		}

class ProjectTaskForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = ('taskname', 'taskdescription', 'plannedstartdate', 
			'plannedcompletedate', 'actualstartdate', 
			'actualcompletedate','ownedby', 'plannedresource', 'actualresource', 'taskstatus')
		labels = {
			'taskname': 'Task Name',
			'taskdescription': 'Description',
			'plannedstartdate': 'Planned Start',
			'plannedcompletedate': 'Planned End',
			'actualstartdate': 'Actual Start',
			'actualcompletedate': 'Actual End',
			'ownedby': 'Action by',
			'plannedresource': 'Planned Resource',
			'actualresource': 'Actual Resource',
			'taskstatus': 'Status',
		}
		widgets = {
			'plannedstartdate': DateInput(attrs={'type': 'date'}),
			'plannedcompletedate': DateInput(attrs={'type': 'date'}),
			'actualstartdate': DateInput(attrs={'type': 'date'}),
			'actualcompletedate': DateInput(attrs={'type': 'date'}),
		}

projectcm-original/projectcm_core/templates/projectcm_core/add_staff_existing.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
 <div class="container fluid">
	<form>
	{% csrf_token %}
	<div class="two_column_grid_row">
	<label for="username"><h5>Search by User Name/Email</h5></label>
		<input type="text" class="form-control-plaintext inputsm" id="username" name="username" value="" placeholder="email/username">
	</div>
	<div class="two_column_grid_row">
		<span></span>
		<button type="submit" class="btn btn-default">Search</button>
	</div>
	</form>
	
	<div class="two_column_grid_row">
	<span><h5>Search Result</h5></span>
	<span></span>
	</div>
	{% if users %}
	<div class="seven_column_grid_row grid_header">
	<span>Username</span>
	<span>First Name</span>
	<span>Last Name</span>
	<span>Email</span>
	<span>Company Admin?</span>
	<span>Is Staff?</span>
	<span></span>
	</div>
		{% for user in users %}
		<div class="seven_column_grid_row_alt">
		<span>{{ user.username }}</span>
		<span>{{ user.first_name }}</span>
		<span>{{ user.last_name }}</span>
		<span>{{ user.email }}</span>
		<span><input type="checkbox"> Admin</span>
		<span><a href="#">Add this staff</a></span>
		<span><a href="#">profile</a></span>
		</div>
		{% endfor %}

	{% else %}
	<div class="one_column_grid">
	No search result
	</div>
	{% endif %}
 </div>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/company_admin_listall.html
{% extends 'common/base.html' %}

{% block content %}

<div class="tableContentLayout">
{% if company_admin_list  %}
{% for company in company_admin_list %}
<div class="tableContent">
<span>{{ company.company_name }}</span>
<span><a href="company/{{ company.id }}/modify" class="btn btn-primary btn-sm" role="button" aria-disabled="true">Modify</a></span>
<span><a href="company/{{ company.id }}/delete" class="btn btn-primary btn-sm" role="button" aria-disabled="true
">Delete</a></span>
</div>

{% endfor %}
{% endif %}
</div>

{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/company_admin_modify.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<form method="POST" class="post-form">
{% csrf_token %}
<!- form.as_ul -->
 <div class="container fluid">
	<div class="two_column_grid_row">
	<label for="company_name"><h5>Company Name</h5></label>
		<input type="text" class="form-control-plaintext inputsm" id="company_name" name="company_name" value="ABC Company">
	</div>
	<div class="one_column_grid_row" style="text-align=left;">
		<h5>Staffs</h5>
	</div>
	<div class="three_column_grid_row" style="text-align=right !important">
		<span></span>
		<span><a href="#" class="btn btn-primary" role="button">Add New Account as Company Staff</a></span>
		<span><a href="{{ request.path }}/addstaff" class="btn btn-primary" role="button">Add Existing Account as Company Staff</a></span>
	</div>

	<div class="seven_column_grid_row grid_header">
		<span>Username</span>
		<span>First Name</span>
		<span>Last Name</span>
		<span>Email</span>
		<span>Company Admin</span>
		<span></span>
		<span></span>
	</div>	
	{% for staff in staffs %}
	<div class="seven_column_grid_row_alt">
		<span>{{ staff.username }}</span>
		<span>{{ staff.first_name }}</span>
		<span>{{ staff.last_name}}</span>
		<span>{{ staff.email }}</span>
		<span></span>
		<span><a href="#">Modify</a></span>
		<span><a href="#">Unstaff</a><br><a href="#">Delete</a></span>
	</div>
	{% endfor %}
		<h5>Holiday settings</h5>
	</div>
 </div>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/listall.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container-fluid">
<div class="row">
<div class="tasks_column col-lg-10">
<p><h5>Tasks</h5></p>
<p>
<span><button type="button" class="btn btn-link"><a href="{{ request.path }}?taskstatus=ALL">All</a></button></span>
<span><button type="button" class="btn btn-link" ><a href="{{ request.path }}?taskstatus=INPROGRESS">In Progress</a></button></span>
<span><button type="button" class="btn btn-link"><a href="{{ request.path }}?taskstatus=COMPLETED">Completed</a></button></span>
<span><button type="button" class="btn btn-link"><a href="{{ request.path }}?taskstatus=OPEN">Open</a></button></span>
</p>
<table class="table">
<thead>
  <tr>
    <th scope="col"></th>
    <th scope="col">Task</th>
    <th scope="col">Description</th>
    <th scope="col">Planned Start</th>
    <th scope="col">Planned End</th>
    <th scope="col">Actual Start</th>
    <th scope="col">Actual End</th>
    <th scope="col">Owner</th>
    <th scope="col">Status</th>
    <th scope="col">Project</th>
    <th scope="col"></td>
  </tr>
</thead>
{% if task_list %}
{% for task in task_list %}
<div class="tasks">
<tr>
<th scope="row"></th>
<td>{{ task.taskname }}</td>
<td>{{ task.taskdescription }}</td>
<td>{{ task.plannedstartdate }}</td>
<td>{{ task.plannedcompletedate }}</td>
<td>{{ task.actualstartdate }}</td>
<td>{{ task.actualcompletedate }}</td>
<td>{{ task.ownedby }}</td>
<td>{{ task.taskstatus }}</td>
<td>{{ task.project.pjname }}</td>
<td><button type="button" class="btn btn-light"><a href="{{ request.path }}task/{{ task.id }}">Update</a></button></td>
</tr>
</div>
{% endfor %}
{% else %}
<div class="message">
<p>No task</p>
</div>
{% endif %}
</table>
</div>

<div class="projects_column col-lg-2">
{% if project_list %}
{% for project in project_list %}
<div class="project">
<p><table class="table">
<tr>
<td>Project:</td>
<td> <a href="{{ project.id }}">{{ project.pjname }}</a></td>
</tr>
<tr>
<td>Company:</td>
<td>{{ project.company }}</td>
</tr>
<tr>
<td>Created by:</td>
<td>{{ project.created_by }}</td>
</tr>


</table></p>
</div>
{% endfor %}
{% else %}
<div class="message">
<p>No projects to show</p>
</div>
{% endif %}
</div>
</div>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/listall2.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container-fluid">
<div class="row">
<div class="col-lg-8">
<h1>Tasks</h1>
</div>
<div class="col-lg-4">
<h1>Projects</h1>
</div>
</div>
</div>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/login.html
<html>
<body>
<form>
<input type='textfield' name='login'>
<input type='password' name='password'>
<input type='button'>
</form>
</body>
</html>

projectcm-original/projectcm_core/templates/projectcm_core/project_edit.html
{% extends 'common/base.html' %}

{% block content %}
<form method="POST" class="post-form">
{% csrf_token %}
{{ form.as_p }}
	<button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/project_listall.html
{% extends 'common/base.html' %}

{% block content %}

<div class="tableContentLayout">
{% if project_manage_list %}
{% for project in project_manage_list %}
<div class="tableContent">
<span>{{ project.pjname }}</span>
<span><a href="manage/{{ project.id }}/modify" class="btn btn-primary btn-sm" role="button" aria-disabled="true">Modify</a></span>
<span><a href="manage/{{ project.id }}/delete" class="btn btn-primary btn-sm" role="button" aria-disabled="true
">Delete</a></span>
<span><a href="manage/{{ project.id }}/role" class="btn btn-primary btn-sm" role="button" aria-disabled="true" >Role</a></span>
<span><a href="manage/{{ project.id }}/task" class="btn btn-primary btn-sm" role="button" aria-disabled="true">Tasks</a></span>
</div>

{% endfor %}
{% endif %}
</div>

{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/project_new.html
{% extends 'common/base.html' %}

{% block content %}
<form method="POST" class="post-form">
{% csrf_token %}
{{ form.as_p }}
	<button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/project_role_modify.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<form method="POST" class="post-form">
{% csrf_token %}
{{ form.as_ul }}
<button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/project_task_list.html
{% extends 'common/base.html' %}

{% block content %}
<!-- populate the member list -->

        {% if projectmember %}
                <div class="projectmembers" style="display: none;">
                {% for member in projectmember %}
                        <span>{{ member.projectuser }}</span>
                {% endfor %}
                </div>
        {% endif %}


<!- populate the tasklist data -->
{% if project_task_list %}
	<div class="readonly_tasklists" style="display: none;">
	{% for task in project_task_list %}
		<div class="task_lists">
			<span id="task_{{ forloop.counter }}_0">{{ task.id }}</span>
			<span id="task_{{ forloop.counter }}_1">{{ task.taskname }}</span>
			<span id="task_{{ forloop.counter }}_2">{{ task.taskdescription }}</span>
			<span id="task_{{ forloop.counter }}_3">{{ task.plannedstartdate | date:"Y-m-d" }}</span>
			<span id="task_{{ forloop.counter }}_4">{{ task.plannedcompletedate | date:"Y-m-d" }}</span>
			<span id="task_{{ forloop.counter }}_5">{{ task.actualstartdate | date:"Y-m-d" }}</span>
			<span id="task_{{ forloop.counter }}_6">{{ task.actualcompletedate | date:"Y-m-d" }}</span>
			<span id="task_{{ forloop.counter }}_7">{{ task.ownedby }}</span>
			<span id="task_{{ forloop.counter }}_8">{{ task.plannedresource }}</span>
			<span id="task_{{ forloop.counter }}_9">{{ task.actualresource }}</span>
			<span id="task_{{ forloop.counter }}_10">{{ task.taskstatus }}</span>
		</div>
	{% endfor %}
	</div>
{% endif %}


<div class="row">
<p>
<h4>Task in this project  
{% if project %}
- {{ project.pjname }}
{% else %}
- unknown
{% endif %}
</h4>
</p>
<div class="task_form">
<div class="task_form_header">
<span></span>
<span><h5>Task Name</h5></span>
<span><h5>Task Description</h5></span>
<span><h5>Planned Start Date</h5></span>
<span><h5>Planned End Date</h5></span>
<span><h5>Actual Start Date</h5></span>
<span><h5>Actual End Date</h5></span>
<span><h5>Action by</h5></span>
<span><h5>Planned Resource</h5></span>
<span><h5>Actual Resource</h5></span>
<span><h5>Status</h5></span>
<span></span>
<span></span>
</div>
{% if project_task_list %}
{% for task in project_task_list %}
<div class="task_form_items">
<form id="form_t_{{ forloop.counter }}" action="task/{{ task.id }}/modify" method="POST">
{% csrf_token %}
<div class="task_lists_form">
<span><a href="task/{{ task.id }}/up"><i class="fas fa-angle-up"></i></a>
<a href="task/{{ task.id }}/down""><i class="fas fa-angle-down"></i></a>
</span>
<span><div class="task_name"><input type="text" class="form-control-plaintext inputsm" id="taskform_{{ forloop.counter }}_1" name="taskname" value="{{ task.taskname }}"></div></span>
<span><textarea class="form-control-plaintext inputsm" id="taskform_{{ forloop.counter }}_2" name="taskdescription">{{ task.taskdescription }}</textarea></span>
<span><input type="date" class="form-control inputsm" id="taskform_{{ forloop.counter }}_3" name="plannedstartdate" style="width: 120px;" value='{{ task.plannedstartdate | date:"Y-m-d" }}'></span>
<span><input type="date" class="form-control inputsm" id="taskform_{{ forloop.counter }}_4" style="width:120px;" name="plannedcompletedate" value="{{ task.plannedcompletedate | date:'Y-m-d' }}"></span>
<span><input type="date" class="form-control inputsm" id="taskform_{{ forloop.counter }}_5" name="actualstartdate" style="width:120px;" value="{{ task.actualstartdate | date:'Y-m-d' }}"></span>
<span><input type="date" class="form-control inputsm" id="taskform_{{ forloop.counter }}_6" name="actualcompletedate" style="width:120px;" value="{{ task.actualcompletedate | date:'Y-m-d' }}"></span>
<span><select class="form-control inputsm" id="taskform_{{ forloop.counter }}_7" name="ownedby" style="width:120px;">
	{% for member in projectmember %}
	<option {% if task.ownedby.id == member.projectuser.id %}selected="selected" {% endif %} value="{{ member.projectuser.id }}">{{ member.projectuser }}</option>
	{% endfor %}
</select></span>
<span><input type="number" class="form-control inputsm" id="taskform_{{ forloop.counter }}_8" name="plannedresource" style="width:120px;" value="{{ task.plannedresource  }}"></span>
<span><input type="number" class="form-control inputsm" id="taskform_{{ forloop.counter }}_9" name="actualresource" style="width:120px;" value="{{ task.actualresource }}"></span>
<span><select class="form-control inputsm" id="taskform_{{ forloop.counter }}_10" name="taskstatus" style="width:120px;">
	<option value="OPEN" {% if task.taskstatus == 'OPEN' %} selected {% endif %}>Open</option>
	<option value="INPROGRESS" {% if task.taskstatus == 'INPROGRESS' %} selected {% endif %}>In Progress</option>
	<option value="COMPLETED" {% if task.taskstatus == 'COMPLETED' %} selected {% endif %}>Completed</option>
</select></span>


<span><a href="javascript:{}" class="btn btn-primary btn-xs" role="button" aria-disabled="true" onclick="document.getElementById('form_t_{{ forloop.counter }}').submit();">Save</a></span>
</form>

<span><a href="task/{{ task.id }}/delete" class="btn btn-primary btn-xs" role="button" aria-disabled="true">Delete</a></span>
</div><!-- End of Task Form Item -->
</div><!-- End of task_form_items -->
{% endfor %}
{% else %} 
<div class="task_form_items"><span>No Task List for this project</span>
</div>
{% endif %}

<div class="task_form_items">
<form method="POST" action="task/add" id="add-task-inline">
{% csrf_token %}
<div class="task_lists_form">
<span></span>
<span><input type="text" class="form-control-plaintext inputsm" name="taskname" maxlength="40" required id="id_taskname"></span>
<span><textarea name="taskdescription" class="form-control-plaintext inputsm" id="idtaskdescription"></textarea></span>
<span><input type="date" name="plannedstartdate" class="form-control inputsm" style="width: 120px;" id="id_plannedstartdate"></span>
<span><input type="date" name="plannedcompletedate" class="form-control inputsm" style="width: 120px;" id="id_plannedcopletedate"></span>
<span><input type="date" name="actualstartdate" class="form-control inputsm" style="width:120px;" id="id_actualstartdate"></span>
<span><input type="date" name="actualcompletedate" class="form-control inputsm" style="width:120px;" id="id_actualcompletedate"></span>
<span><select name="ownedby" class="form-control inputsm" required style="width: 120px;" id="id_owndedby">
	{% for member in projectmember %}
	<option value="{{ member.projectuser.id }}">{{ member.projectuser }}</option>
	{% endfor %}
</select>
</span>

<span><input type="number" name="plannedresource" class="form-control inputsm" style="width:120px;" id="id_plannedresource"></span>
<span><input type="number" name="actualresource" class="form-control inputsm" id="id_actualresource" style="width: 120px;"></span>


<span><select class="form-control inputsm" id="taskform_{{ forloop.counter }}_10" name="taskstatus" style="width:120px;">
        <option value="OPEN">Open</option>
        <option value="INPROGRESS">In Progress</option>
        <option value="COMPLETED">Completed</option>
</select></span>


<span><a href="javascript:{}" class="btn btn-info btn-xs" role="button" aria-disabled="true" onclick="document.getElementById('add-task-inline').submit();">Add</a></span>
<span></span>
		</div>
</form>
</div>	
<div class="dynamic-gantt gantt">
			<script>drawGanttFromElement();</script>
</div>

<div class="dynamic-resource gantt">
			<script>drawResourcePanel();</script>
</div>

{% endblock %}

projectcm-original/projectcm_core/templates/projectcm_core/project_task_modify.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<form method="POST" class="post-form">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr><td colspan="2"><button type="submit" class="save btn btn-default">Save</button></td>
</form>
</table>
{% endblock %}